### PR TITLE
Set query-insights plugin 3.0.0 baseline JDK version to JDK-21

### PR DESCRIPTION
**Pull request by reta**
### Description
Set query-insights plugin 3.0.0 baseline JDK version to JDK-21

### Issues Resolved
Closes https://github.com/opensearch-project/query-insights/issues/134

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@ansjcy @dzane17 @deshsidd mind please taking a look? thank you

**Review by dzane17 — APPROVED** [review]

**Comment by dzane17** [comment]
Thanks @reta

**Comment by dzane17** [comment]
@reta JDK update is only on `main` right? Seems like some of these changes are needed to fix 2.x build. Added them here: https://github.com/opensearch-project/query-insights/pull/171

**Comment by reta** [comment]
> @reta JDK update is only on main right?

Yes, only `main`, thanks @dzane17

**Pull request merged**
