### PR TITLE
Create health_stats API for query insights

### PR DESCRIPTION
**Pull request by ansjcy**
### Description
Create healthstats API for query insights, using the data model from https://github.com/opensearch-project/query-insights/pull/120

### Issues Resolved
Related to https://github.com/opensearch-project/query-insights/issues/9

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ansjcy** [comment]
The build will fail until we rebase https://github.com/opensearch-project/query-insights/pull/120

**Comment by deshsidd** [comment]
Looks like builds/tests and hygiene failing. Now that we have merged #120 - Let me know when this is ready to review @ansjcy

**Comment by ansjcy** [comment]
@deshsidd just rebased and this PR should be ready.

**Comment by deshsidd** [comment]
LGTM

**Review by deshsidd — APPROVED** [review]

**Pull request merged**
